In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
AV = pd.read_csv("runs\sumo-v0\DQN_sumo-v0_log_32_1.csv",index_col=None)

In [8]:
AV[""]

,episode,timestep,reward,if_collision,collision_rate,adversarial_counts,epsilon,av_speed_avg,av_total_risk_avg,av_distance,av_running_time,av_acc_avg,av_dece_avg,av_left_avg,av_right_avg,Unnamed: 15
0,0,3000,-8450.4755,0,0.000000,2999,1.000000,2.410016,-0.012395,723.221073,360.1,2.999000,0.000000,0.087000,0.095333,NaN
1,1,5724,-7263.9026,0,0.000000,5723,1.000000,3.661009,0.213470,994.898252,332.5,2.998899,-0.946709,0.095815,0.088473,NaN
2,2,7127,-4246.4410,1,0.333333,7126,1.000000,0.860409,-0.442380,120.713484,200.4,2.997863,0.000000,0.076265,0.088382,NaN
3,3,10127,-8529.6211,0,0.250000,8997,0.630466,2.170897,0.127334,651.379479,360.1,2.999000,0.000000,0.090667,0.092333,NaN
4,4,10291,-493.7571,1,0.400000,9123,0.775085,1.100017,-0.431817,17.977576,76.5,2.981818,0.000000,0.091463,0.109756,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,304,443425,1794.7368,0,0.511475,186732,0.376536,30.785022,-0.032205,6994.941718,287.3,2.997404,0.000000,0.098592,0.087588,NaN
305,305,443599,-120.7518,1,0.513072,186794,0.378523,18.123271,-0.046478,314.184766,77.5,2.982857,0.000000,0.327586,0.178161,NaN
306,306,443770,-123.4889,1,0.514658,186861,0.376637,18.033259,-0.097355,307.151967,77.2,2.982558,0.000000,0.415205,0.146199,NaN
307,307,446076,1632.5872,0,0.512987,187730,0.374770,30.330090,-0.172484,6994.330643,290.7,2.998246,0.000000,0.052905,0.072420,NaN
308,308,446244,-118.6512,1,0.514563,187778,0.376737,18.049490,-0.100649,302.062242,76.9,2.982249,0.000000,0.333333,0.273810,NaN

In [ ]:
plt.plot(AV[""])